FROM node:16-alpine
     
USER node
 
RUN mkdir -p /home/node/app
WORKDIR /home/node/app

#Para o docker build
COPY package.json . 

COPY --chown=node:node ./package.json ./
RUN npm install
COPY --chown=node:node ./ ./

#Para o docker build
COPY . .

CMD ["npm", "start"]