version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes:
      - /home/node/app/node_modules #Do not try to map this folder in the container
      - .:/home/node/app # Queremos mapear a ficheiro atual (.) ao ficheiro /app dentro do container 
  # tests:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - /home/node/app/node_modules 
  #     - .:/home/node/app 
  #   command: ["npm", "run", "test"]

